export const CountriesTypes = {
  GET_COUNTRIES: '[COUNTRIES]: GET_COUNTRIES',
  ERROR_GET_COUNTRIES: '[COUNTRIES] ERROR_GET_COUNTRIES',
  FILTER_BY_REGION: '[COUNTRIES]: FILTER_BY_REGION',
  FILTER_BY_NAME: '[COUNTRIES]: FILTER_BY_NAME',
};
